from tkinter import *
def TinhBMI() :
    a=float(cao.get())
    b=float(nang.get())
    Bmi=b/(a*a)
    BMI.set(Bmi)
    if Bmi<18.5 :
        TT.set("Gầy")
        NguyCo.set("Thấp")
    elif Bmi>=18.5 and Bmi<=24.9 :
        TT.set("Bình Thường")
        NguyCo.set("Trung Bình")
    elif Bmi>=25 and Bmi<=29.9 :
        TT.set("Mập")
        NguyCo.set("Cao")
    elif Bmi>=30 :
        TT.set("Béo Phì")
        NguyCo.set("Rất Cao")
root=Tk()
root.title("Đo BMI")
root.minsize(height=150,width=250)
root.resizable(height=True,width=True)
cao=StringVar()
nang=StringVar()
BMI=StringVar()
TT=StringVar()
NguyCo=StringVar()
Label(root,text="Máy tính BMI",justify=CENTER).grid(row=0,columnspan=3)
Label(root,text="Chiều Cao :").grid(row=1,column=0)
Entry(root,width=50,textvariable=cao).grid(row=1,column=1)
Label(root,text="Cân Nặng :").grid(row=2,column=0)
Entry(root,width=50,textvariable=nang).grid(row=2,column=1)
Nut=Frame()
Button(Nut,text="Tính BMI",justify=CENTER,command=TinhBMI).pack(side=LEFT)
Nut.grid(row=3,columnspan=2)
Label(root,text="BMI của bạn :").grid(row=4,column=0)
Entry(root,width=50,textvariable=BMI).grid(row=4,column=1)
Label(root,text="Tình trạng của bạn :").grid(row=5,column=0)
Entry(root,width=50,textvariable=TT).grid(row=5,column=1)
Label(root,text="Nguy cơ phát triển bệnh :").grid(row=6,column=0)
Entry(root,width=50,textvariable=NguyCo).grid(row=6,column=1)
Thoat=Frame()
Button(Thoat,text="Thoát",justify=CENTER,command=root.quit).pack(side=LEFT)
Thoat.grid(row=7,columnspan=2)
root.mainloop()