from tkinter import *
def ChuyenC() :
    f=float(Dof.get())
    DoC.set((f-32)/1.8)    
root=Tk()
root.title("Chuyển độ f sang độ c")
root.minsize(height=150,width=250)
root.resizable(height=True,width=True)
Dof=StringVar()
DoC=StringVar()
Label(root,text="Nhập độ F").grid(row=0,column=0)
Entry(root,width=50,textvariable=Dof).grid(row=0,column=1)
Nut=Frame()
Button(Nut,text="Chuyển",justify=CENTER,command=ChuyenC).pack(side=LEFT)
Nut.grid(row=1,columnspan=2)
Label(root,text="Độ C").grid(row=2,column=0)
Entry(root,width=50,textvariable=DoC).grid(row=2,column=1)
Nut1=Frame()
Button(Nut1,text="Thoát",justify=CENTER,command=root.quit).pack(side=LEFT)
Nut1.grid(row=3,columnspan=2)   
root.mainloop()